-- =====================================================
-- Enable RLS on tables flagged by Supabase Security Advisor
-- Apply via Supabase Dashboard > SQL Editor
--
-- Two issue types addressed:
--   1. policy_exists_rls_disabled  — policies written but RLS switch off
--   2. rls_disabled_in_public      — no RLS at all on public tables
--
-- NOTE: The SECURITY DEFINER view warnings are a separate issue.
--       Those views (course_enrollment_summary, profiles, etc.) were
--       generated by Figma Make. Fixing them requires recreating the
--       views without SECURITY DEFINER and is deferred to a future
--       migration once the view definitions are reviewed.
-- =====================================================


-- ─── 1. users ─────────────────────────────────────────────────────────────────
-- RLS policies already exist but the switch was never turned on.
-- Flipping this makes all existing policies take effect immediately.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;


-- ─── 2. bookmarks ─────────────────────────────────────────────────────────────
-- Users manage their own bookmarks only.
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "bookmarks_own"
  ON public.bookmarks
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- ─── 3. offering_interest ─────────────────────────────────────────────────────
-- Users can express and view their own interest in offerings.
-- Admins can read all (needed for analytics/reporting).
ALTER TABLE public.offering_interest ENABLE ROW LEVEL SECURITY;

CREATE POLICY "offering_interest_own"
  ON public.offering_interest
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "offering_interest_admin_read"
  ON public.offering_interest
  FOR SELECT
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('admin', 'super'))
  );


-- ─── 4. prompt_uses ───────────────────────────────────────────────────────────
-- Users see their own prompt usage history.
ALTER TABLE public.prompt_uses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "prompt_uses_own"
  ON public.prompt_uses
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- ─── 5. event_companions ──────────────────────────────────────────────────────
-- Authenticated users can view event companions.
-- Only the creator can modify their own companion listing.
ALTER TABLE public.event_companions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "event_companions_read_authenticated"
  ON public.event_companions
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "event_companions_write_own"
  ON public.event_companions
  FOR ALL
  USING (auth.uid() = created_by)
  WITH CHECK (auth.uid() = created_by);


-- ─── 6. event_companion_items ─────────────────────────────────────────────────
-- Read access for all authenticated users.
-- Write access only via the service role (managed through event_companions).
ALTER TABLE public.event_companion_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "event_companion_items_read_authenticated"
  ON public.event_companion_items
  FOR SELECT
  USING (auth.uid() IS NOT NULL);


-- ─── 7. prompts ───────────────────────────────────────────────────────────────
-- Shared content — authenticated users can read.
-- Only admins can create/update/delete prompts.
ALTER TABLE public.prompts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "prompts_read_authenticated"
  ON public.prompts
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "prompts_write_admin"
  ON public.prompts
  FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('admin', 'super'))
  );


-- ─── 8. program_prompts ───────────────────────────────────────────────────────
-- Junction table linking programs to prompts — read for authenticated.
ALTER TABLE public.program_prompts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "program_prompts_read_authenticated"
  ON public.program_prompts
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "program_prompts_write_admin"
  ON public.program_prompts
  FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('admin', 'super'))
  );


-- ─── 9. membership_tier_permissions ───────────────────────────────────────────
-- Reference/lookup table — all authenticated users need to read this
-- to determine what features their membership tier unlocks.
ALTER TABLE public.membership_tier_permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "membership_tier_permissions_read_authenticated"
  ON public.membership_tier_permissions
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "membership_tier_permissions_write_admin"
  ON public.membership_tier_permissions
  FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('admin', 'super'))
  );


-- ─── 10. product_mappings ─────────────────────────────────────────────────────
-- Maps payment products to platform offerings.
-- Readable by authenticated users (needed at checkout/upgrade flows).
ALTER TABLE public.product_mappings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "product_mappings_read_authenticated"
  ON public.product_mappings
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "product_mappings_write_admin"
  ON public.product_mappings
  FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('admin', 'super'))
  );


-- ─── 11. offering_marketing_templates ─────────────────────────────────────────
-- Admin-managed marketing copy for offerings.
ALTER TABLE public.offering_marketing_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "offering_marketing_templates_read_authenticated"
  ON public.offering_marketing_templates
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "offering_marketing_templates_write_admin"
  ON public.offering_marketing_templates
  FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('admin', 'super'))
  );
